[package]
name = "cli-client"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.130"
serde_json = "1.0.68"
clap = "2.33.3"
dirs-next = "2.0.0"
borsh = "0.9.3"

[[bin]]
name = "cli-client"
path = "src/main.rs"
